import type { Metadata } from "next";
import "./styles/globals.css";
import Navigation from "./components/navigation";
import { getServerSession } from "next-auth";
import SessionProvider  from '@/app/components/SessionProvider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {

  const session = await getServerSession()

  return (
    <html lang="en">

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet"></link>
      </head>

      <body>
        <SessionProvider>
          <div className="container">
            <Navigation />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}


